name: Daily Antipodle JSON Generator

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:     # allows manual trigger too

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install geopandas pandas pyogrio

    - name: Generate antipodle.json
      run: python backend/app.py

    - name: Push updated file
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/akdamitio/antipodle.git
        git add docs/data/antipodle.json
        git commit -m "Auto-update antipodle.json for ${{ steps.date.outputs.today }}"
        git push origin HEAD:main
